const fs = require('fs');
const path = require('path');

// Function to generate environment file
const generateEnvFile = (targetFileName, isProduction, apiUrl) => {
  const targetPath = path.join(__dirname, `../src/environments/${targetFileName}`);
  const envConfigFile = `// This file was autogenerated by set-env.js
import packageInfo from '../../package.json';

export const environment = {
  appVersion: packageInfo.version,
  production: ${isProduction},
  apiUrl: '${apiUrl}'
};
`;
  fs.writeFileSync(targetPath, envConfigFile, { encoding: 'utf8' });
  console.log(`Generated ${targetFileName} with apiUrl: ${apiUrl}`);
};

// Get the API URL from environment variables
// For local development, we usually use '/api' to trigger the proxy
const apiUrl = process.env.API_URL || '/api';

generateEnvFile('environment.ts', false, '/api'); // Always use proxy for dev
generateEnvFile('environment.prod.ts', true, apiUrl);
